### ISSUE TITLE
my-hit плагин устарел и не работает

### ISSUE THREAD

**Issue by tarasius** [seppius-xbmc-repo/ru#20]
Здравствуйте. Из описания не ясно ведёте ли вы поддержку и плагинов также, или только репозитория?
Если поддерживаете плагины, то вот проблема. Плагин портала my-hit поменял код веб-страниц и плагин не отрывается, ломаясь при парсинге сайта.
```
Error Type: <type 'exceptions.AttributeError'>
Error Contents: 'NoneType' object has no attribute 'find'
Traceback (most recent call last):
File "/home/pi/.kodi/addons/plugin.video.my-hit.ru/default.py", line 1255, in <module>                                                Movie_List(params)
File "/home/pi/.kodi/addons/plugin.video.my-hit.ru/default.py", line 310, in Movie_List                                                pinfo = soup.find('div', {'class':"col-sm-10 col-md-8"}).find('div', {'class':"col-sm-3"}).text.split(':')[1].re                                                                     place('(','').replace(')','')
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by xbmcrus** [comment]
Исправлено. обновляйтесь

**Comment by seppius-xbmc-repo** [comment]
Автор больше не ведёт свои плагины. Но, исправлено, обновляйтесь до 1.2.5

**Comment by tarasius** [comment]
Спасибо большое =)
