### ISSUE TITLE
plugin.fs.ua 1.9.33 перестал работать после обновления

### ISSUE THREAD

**Issue by vkravets** [seppius-xbmc-repo/ru#22]
При попытки войти в папку Видео вываливается ошибка. Все остальное как это не странно звучит - работает )
XBMC LOG:
```
16:07:18 T:18446744072341341536   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.HTTPError'>
                                            Error Contents: HTTP Error 400: Bad Request
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fs.ua/default.py", line 950, in <module>
                                                func(execution_params)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fs.ua/default.py", line 223, in get_categories
                                                'filter': '',
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fs.ua/default.py", line 455, in readcategory
                                                http = client.GET(categoryUrl, httpSiteUrl)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.fs.ua/lib/httpclient.py", line 54, in GET
                                                response = opener.open(req)
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 397, in open
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 510, in http_response
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 435, in error
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 369, in _call_chain
                                              File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/urllib2.py", line 518, in http_error_default
                                            HTTPError: HTTP Error 400: Bad Request
                                            -->End of Python script error report<--
16:07:19 T:18446744072292791312   ERROR: static bool XFILE::CDirectory::GetDirectory(const CURL&, CFileItemList&, const XFILE::CDirectory::CHints&, bool) - Error getting plugin://plugin.video.fs.ua/?category=video&firstPage=yes&href=http%3a%2f%2ffs.to&mode=get_categories
16:07:19 T:18446744072292791312   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fs.ua/?category=video&firstPage=yes&href=http%3a%2f%2ffs.to&mode=get_categories) failed
***
```

**Comment by lynx-ua** [comment]
+1

**Comment by vkravets** [comment]
Нашел, пофиксил, проверил... Надеюсь поможет )

**Comment by JaxxC** [comment]
Все так же не работает, проверял на Ubuntu 15.04 и Rpi2.

> 14:03:18 T:140029884098304  NOTICE: ES: Starting UDP Event server on 127.0.0.1:9777
14:03:18 T:140029884098304  NOTICE: UDP: Listening on port 9777
14:03:44 T:140031839590400   ERROR: GetDirectory - Error getting plugin://plugin.video.fs.ua/?category=video&firstPage=yes&href
=http%3a%2f%2ffs.to&mode=get_categories
14:03:44 T:140031839590400   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fs.ua/?category=video&firstPage=yes&hre
f=http%3a%2f%2ffs.to&mode=get_categories) failed

**Comment by vkravets** [comment]
из того что я вижу фикс не применился

**Comment by vkravets** [comment]
У меня все работает с этим фиксом... Какой полный стектрейс?

**Comment by JaxxC** [comment]
По сути это и есть полный стектрейс, при открытии "Видео",  выскакивает "Ошибка: неизвестная страница" в лог падают эти две строчки, и все 

> 15:05:26 T:139989783074816   ERROR: GetDirectory - Error getting plugin://plugin.video.fs.ua/?category=video&firstPage=yes&href
=http%3a%2f%2ffs.to&mode=get_categories
15:05:26 T:139989783074816   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.fs.ua/?category=video&firstPage=yes&hre
f=http%3a%2f%2ffs.to&mode=get_categories) failed

**Comment by JaxxC** [comment]
Сносил плагин и ставил заново, ошибка воспроизводится(

**Comment by vkravets** [comment]
Ну вот и замечательно, осталось, чтоб это кто-то замерджил, обновил версию и зарелизил новую версию....
